<?php

namespace App\Console\Commands;

use App\Models\Role;
use App\Support\PermissionCatalogue;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

final class ExportPermissionsCommand extends Command
{
    protected $signature = 'ir4:export-permissions';

    protected $description = 'Write PERMISSIONS.md and update the Permission union in enums.ts';

    public function handle(): int
    {
        $this->writeMarkdown();
        $this->writeTypeScriptUnion();

        $this->info('Wrote PERMISSIONS.md and Permission union in enums.ts');

        return self::SUCCESS;
    }

    private function writeMarkdown(): void
    {
        $lines = [
            '# IR4 Permissions',
            '',
            '> Generated by `php artisan ir4:export-permissions`. Reflects the live database role matrix.',
            '',
            '## Catalogue',
            '',
        ];

        foreach (PermissionCatalogue::grouped() as $group => $permissions) {
            $lines[] = "### {$group}";
            $lines[] = '';
            foreach ($permissions as $permission) {
                $lines[] = "- `{$permission}`";
            }
            $lines[] = '';
        }

        $roles = Role::query()
            ->where('guard_name', PermissionCatalogue::GUARD)
            ->orderByDesc('is_system')
            ->orderBy('name')
            ->with('permissions')
            ->get();

        $lines[] = '## Role matrix';
        $lines[] = '';
        $lines[] = '| Role | Flags | Permissions |';
        $lines[] = '|---|---|---|';

        foreach ($roles as $role) {
            $flags = [];
            if ($role->is_system) {
                $flags[] = 'system';
            }
            if ($role->is_read_only) {
                $flags[] = 'read-only';
            }
            $flagText = $flags === [] ? '—' : implode(', ', $flags);

            if ($role->is_system) {
                $permText = '_all_';
            } else {
                $names = $role->permissions->pluck('name')->sort()->values()->all();
                $permText = $names === [] ? '_none_' : '`'.implode('`, `', $names).'`';
            }

            $lines[] = "| {$role->name} | {$flagText} | {$permText} |";
        }

        $lines[] = '';

        File::put(base_path('PERMISSIONS.md'), implode("\n", $lines));
    }

    private function writeTypeScriptUnion(): void
    {
        $path = resource_path('js/types/enums.ts');
        $existing = File::exists($path) ? File::get($path) : "// AUTO-GENERATED by `php artisan ir4:export-enums`. Do not edit by hand.\n\n";

        $existing = preg_replace(
            '/\n\/\/ --- Permission catalogue \(DOC-03\) ---.*$/s',
            '',
            $existing,
        ) ?? $existing;

        $cases = [];
        foreach (PermissionCatalogue::all() as $name) {
            $key = str_replace(' ', '', ucwords(str_replace('-', ' ', $name)));
            $cases[] = "  {$key}: '{$name}',";
        }

        $block = implode("\n", [
            '',
            '// --- Permission catalogue (DOC-03) ---',
            '// Updated by `php artisan ir4:export-permissions`.',
            'export const Permission = {',
            ...$cases,
            '} as const;',
            '',
            'export type Permission = (typeof Permission)[keyof typeof Permission];',
            '',
        ]);

        File::put($path, rtrim($existing)."\n".$block);
    }
}
