<?php

namespace App\Console\Commands;

use App\Support\PermissionCatalogue;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;
use Illuminate\Support\Str;
use ReflectionEnum;
use ReflectionEnumBackedCase;
use UnitEnum;

/**
 * Mirror PHP backed enums into resources/js/types/enums.ts (DOC-01 §6).
 *
 *   php artisan ir4:export-enums
 *   php artisan ir4:export-enums --check
 */
final class ExportEnumsCommand extends Command
{
    protected $signature = 'ir4:export-enums {--check : Fail if the committed file is stale}';

    protected $description = 'Write App\\Enums to resources/js/types/enums.ts';

    public function handle(): int
    {
        $path = resource_path('js/types/enums.ts');
        $rendered = $this->render();

        if ($this->option('check')) {
            return $this->assertMatchesCommitted($path, $rendered);
        }

        File::put($path, $rendered);
        $this->formatWithPrettier($path);
        $this->info('Wrote '.$path);

        return self::SUCCESS;
    }

    private function assertMatchesCommitted(string $path, string $rendered): int
    {
        $tmp = storage_path('app/ir4-enums-check.ts');
        File::ensureDirectoryExists(dirname($tmp));
        File::put($tmp, $rendered);
        $this->formatWithPrettier($tmp);

        $committed = File::get($path);
        $generated = File::get($tmp);
        File::delete($tmp);

        if ($committed === $generated) {
            $this->info('enums.ts is in sync with App\\Enums.');

            return self::SUCCESS;
        }

        $this->error('resources/js/types/enums.ts is out of date. Run php artisan ir4:export-enums');

        return self::FAILURE;
    }

    private function formatWithPrettier(string $path): void
    {
        $prettier = base_path('node_modules/.bin/prettier');

        if (! is_file($prettier)) {
            return;
        }

        Process::path(base_path())->run([$prettier, '--write', $path])->throw();
    }

    private function render(): string
    {
        $blocks = [];

        foreach ($this->enumClasses() as $class) {
            $blocks[] = $this->renderEnum($class);
        }

        return "// AUTO-GENERATED by `php artisan ir4:export-enums`. Do not edit by hand.\n\n"
            .implode("\n", $blocks)
            .$this->renderPermissions();
    }

    /**
     * @return list<class-string<UnitEnum>>
     */
    private function enumClasses(): array
    {
        $classes = [];

        foreach (File::files(app_path('Enums')) as $file) {
            $class = 'App\\Enums\\'.$file->getFilenameWithoutExtension();

            if (! enum_exists($class)) {
                continue;
            }

            $reflection = new ReflectionEnum($class);

            if ($reflection->getBackingType()?->getName() !== 'string') {
                continue;
            }

            $classes[] = $class;
        }

        sort($classes);

        return $classes;
    }

    /**
     * @param  class-string<UnitEnum>  $class
     */
    private function renderEnum(string $class): string
    {
        $name = class_basename($class);
        $reflection = new ReflectionEnum($class);
        $constLines = [];
        $labelLines = [];
        $hasLabel = $reflection->hasMethod('label');

        foreach ($reflection->getCases() as $case) {
            if (! $case instanceof ReflectionEnumBackedCase) {
                continue;
            }

            $value = $case->getBackingValue();
            $constLines[] = '    '.$case->getName().': '.$this->jsString($value).',';

            if ($hasLabel && is_string($value)) {
                $label = $reflection->getMethod('label')->invoke($case->getValue());
                $labelLines[] = '    '.$this->jsString($value).': '.$this->jsString($label).',';
            }
        }

        $out = "export const {$name} = {\n"
            .implode("\n", $constLines)."\n"
            ."} as const;\n\n"
            ."export type {$name} =\n"
            ."    (typeof {$name})[keyof typeof {$name}];\n";

        if ($labelLines !== []) {
            $out .= "\nexport const {$name}Labels: Record<{$name}, string> = {\n"
                .implode("\n", $labelLines)."\n"
                ."};\n";
        }

        return $out;
    }

    private function renderPermissions(): string
    {
        $constLines = [];

        foreach (PermissionCatalogue::all() as $permission) {
            $key = Str::studly($permission);
            $constLines[] = '    '.$key.': '.$this->jsString($permission).',';
        }

        return "\n// --- Permission catalogue (DOC-03) ---\n"
            ."export const Permission = {\n"
            .implode("\n", $constLines)."\n"
            ."} as const;\n\n"
            ."export type Permission = (typeof Permission)[keyof typeof Permission];\n";
    }

    private function jsString(mixed $value): string
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
    }
}
