<?php

namespace App\Console\Commands;

use BackedEnum;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use ReflectionEnum;

final class ExportEnumsCommand extends Command
{
    protected $signature = 'ir4:export-enums';

    protected $description = 'Export App\\Enums backed enums to resources/js/types/enums.ts';

    public function handle(): int
    {
        $enumPath = app_path('Enums');
        $outputPath = resource_path('js/types/enums.ts');

        $blocks = [
            '// AUTO-GENERATED by `php artisan ir4:export-enums`. Do not edit by hand.',
            '',
        ];

        if (is_dir($enumPath)) {
            foreach (File::files($enumPath) as $file) {
                if ($file->getExtension() !== 'php') {
                    continue;
                }

                $class = 'App\\Enums\\'.$file->getFilenameWithoutExtension();

                if (! enum_exists($class)) {
                    continue;
                }

                $reflection = new ReflectionEnum($class);

                if (! $reflection->isBacked()) {
                    continue;
                }

                /** @var class-string<BackedEnum> $backedClass */
                $backedClass = $class;
                $blocks[] = $this->renderEnum($backedClass, $reflection);
                $blocks[] = '';
            }
        }

        File::ensureDirectoryExists(dirname($outputPath));

        $permissionBlock = '';
        if (File::exists($outputPath)) {
            $existing = File::get($outputPath);
            if (preg_match('/\n\/\/ --- Permission catalogue \(DOC-03\) ---.*$/s', $existing, $matches) === 1) {
                $permissionBlock = $matches[0];
            }
        }

        File::put($outputPath, rtrim(implode("\n", $blocks))."\n".$permissionBlock);

        $this->info("Wrote {$outputPath}");

        return self::SUCCESS;
    }

    /**
     * @param  class-string<BackedEnum>  $class
     * @param  ReflectionEnum<BackedEnum>  $reflection
     */
    private function renderEnum(string $class, ReflectionEnum $reflection): string
    {
        $name = $reflection->getShortName();
        $cases = [];
        $labels = [];

        foreach ($reflection->getCases() as $case) {
            /** @var BackedEnum $enumCase */
            $enumCase = $case->getValue();
            $value = (string) $enumCase->value;
            $cases[] = "  {$case->getName()}: '{$value}',";

            if (method_exists($enumCase, 'label')) {
                /** @var string $label */
                $label = $enumCase->label();
                $escaped = str_replace("'", "\\'", $label);
                $labels[] = "  '{$value}': '{$escaped}',";
            }
        }

        $lines = [
            "export const {$name} = {",
            ...$cases,
            '} as const;',
            '',
            "export type {$name} = (typeof {$name})[keyof typeof {$name}];",
        ];

        if ($labels !== []) {
            $lines[] = '';
            $lines[] = "export const {$name}Labels: Record<{$name}, string> = {";
            $lines = [...$lines, ...$labels, '};'];
        }

        return implode("\n", $lines);
    }
}
