// AUTO-GENERATED by `php artisan ir4:export-enums`. Do not edit by hand.

export const AccountedSource = {
  MusterReader: 'muster_reader',
  GateExit: 'gate_exit',
  Manual: 'manual',
} as const;

export type AccountedSource = (typeof AccountedSource)[keyof typeof AccountedSource];

export const AccountedSourceLabels: Record<AccountedSource, string> = {
  'muster_reader': 'Muster reader',
  'gate_exit': 'Gate exit',
  'manual': 'Manual',
};

export const AlertSeverity = {
  Info: 'info',
  Warning: 'warning',
  Critical: 'critical',
} as const;

export type AlertSeverity = (typeof AlertSeverity)[keyof typeof AlertSeverity];

export const AlertSeverityLabels: Record<AlertSeverity, string> = {
  'info': 'Info',
  'warning': 'Warning',
  'critical': 'Critical',
};

export const AlertStatus = {
  Open: 'open',
  Acknowledged: 'acknowledged',
  Resolved: 'resolved',
} as const;

export type AlertStatus = (typeof AlertStatus)[keyof typeof AlertStatus];

export const AlertStatusLabels: Record<AlertStatus, string> = {
  'open': 'Open',
  'acknowledged': 'Acknowledged',
  'resolved': 'Resolved',
};

export const AlertType = {
  PpeViolation: 'ppe_violation',
  GasWarning: 'gas_warning',
  GasAlarm: 'gas_alarm',
  RedZoneIntrusion: 'red_zone_intrusion',
  UnauthorizedZoneAccess: 'unauthorized_zone_access',
  ZoneOccupancyExceeded: 'zone_occupancy_exceeded',
  HeightWithoutHarness: 'height_without_harness',
  FallDetection: 'fall_detection',
  StationaryTag: 'stationary_tag',
  WorkerDown: 'worker_down',
  Evacuation: 'evacuation',
  DeviceOffline: 'device_offline',
  CameraOffline: 'camera_offline',
  EquipmentOverdue: 'equipment_overdue',
  ClockSkew: 'clock_skew',
  System: 'system',
} as const;

export type AlertType = (typeof AlertType)[keyof typeof AlertType];

export const AlertTypeLabels: Record<AlertType, string> = {
  'ppe_violation': 'PPE violation',
  'gas_warning': 'Gas warning',
  'gas_alarm': 'Gas alarm',
  'red_zone_intrusion': 'Red zone intrusion',
  'unauthorized_zone_access': 'Unauthorized zone access',
  'zone_occupancy_exceeded': 'Zone occupancy exceeded',
  'height_without_harness': 'Height without harness',
  'fall_detection': 'Fall detection',
  'stationary_tag': 'Stationary tag',
  'worker_down': 'Worker down',
  'evacuation': 'Evacuation',
  'device_offline': 'Device offline',
  'camera_offline': 'Camera offline',
  'equipment_overdue': 'Equipment overdue',
  'clock_skew': 'Clock skew',
  'system': 'System',
};

export const AssetStatus = {
  Active: 'active',
  Maintenance: 'maintenance',
  Offline: 'offline',
} as const;

export type AssetStatus = (typeof AssetStatus)[keyof typeof AssetStatus];

export const AssetStatusLabels: Record<AssetStatus, string> = {
  'active': 'Active',
  'maintenance': 'Maintenance',
  'offline': 'Offline',
};

export const AssetType = {
  Pole: 'pole',
  Gate: 'gate',
  SccServer: 'scc_server',
  SccWorkstation: 'scc_workstation',
  Other: 'other',
} as const;

export type AssetType = (typeof AssetType)[keyof typeof AssetType];

export const AssetTypeLabels: Record<AssetType, string> = {
  'pole': 'Pole',
  'gate': 'Gate',
  'scc_server': 'SCC Server',
  'scc_workstation': 'SCC Workstation',
  'other': 'Other',
};

export const AuditEvent = {
  Login: 'login',
  Logout: 'logout',
  LoginFailed: 'login_failed',
  DataAccess: 'data_access',
  Created: 'created',
  Updated: 'updated',
  Deleted: 'deleted',
  ConfigChanged: 'config_changed',
  Published: 'published',
  Acknowledged: 'acknowledged',
  Exported: 'exported',
  Wiped: 'wiped',
} as const;

export type AuditEvent = (typeof AuditEvent)[keyof typeof AuditEvent];

export const AuditEventLabels: Record<AuditEvent, string> = {
  'login': 'Login',
  'logout': 'Logout',
  'login_failed': 'Login failed',
  'data_access': 'Data access',
  'created': 'Created',
  'updated': 'Updated',
  'deleted': 'Deleted',
  'config_changed': 'Configuration changed',
  'published': 'Published',
  'acknowledged': 'Acknowledged',
  'exported': 'Exported',
  'wiped': 'Wiped',
};

export const CameraType = {
  Fixed: 'fixed',
  Ptz: 'ptz',
  Dome: 'dome',
  Other: 'other',
} as const;

export type CameraType = (typeof CameraType)[keyof typeof CameraType];

export const CameraTypeLabels: Record<CameraType, string> = {
  'fixed': 'Fixed',
  'ptz': 'PTZ',
  'dome': 'Dome',
  'other': 'Other',
};

export const CheckoutState = {
  Available: 'available',
  CheckedOut: 'checked_out',
  OverdueReturn: 'overdue_return',
} as const;

export type CheckoutState = (typeof CheckoutState)[keyof typeof CheckoutState];

export const CheckoutStateLabels: Record<CheckoutState, string> = {
  'available': 'Available',
  'checked_out': 'Checked out',
  'overdue_return': 'Overdue return',
};

export const DeviceType = {
  GasDetector: 'gas_detector',
  Co2Sensor: 'co2_sensor',
  EnvironmentalSensor: 'environmental_sensor',
  RfidReader: 'rfid_reader',
  WifiGateway: 'wifi_gateway',
  Rs485Interface: 'rs485_interface',
  QrPrinter: 'qr_printer',
  EdgeCompute: 'edge_compute',
  Other: 'other',
} as const;

export type DeviceType = (typeof DeviceType)[keyof typeof DeviceType];

export const DeviceTypeLabels: Record<DeviceType, string> = {
  'gas_detector': 'Gas detector',
  'co2_sensor': 'CO₂ sensor',
  'environmental_sensor': 'Environmental sensor',
  'rfid_reader': 'RFID reader',
  'wifi_gateway': 'Wi-Fi gateway',
  'rs485_interface': 'RS485 interface',
  'qr_printer': 'QR printer',
  'edge_compute': 'Edge compute',
  'other': 'Other',
};

export const Direction = {
  In: 'in',
  Out: 'out',
} as const;

export type Direction = (typeof Direction)[keyof typeof Direction];

export const DirectionLabels: Record<Direction, string> = {
  'in': 'In',
  'out': 'Out',
};

export const EntryExitSource = {
  GateReader: 'gate_reader',
  ManualCorrection: 'manual_correction',
  AutoSweep: 'auto_sweep',
} as const;

export type EntryExitSource = (typeof EntryExitSource)[keyof typeof EntryExitSource];

export const EntryExitSourceLabels: Record<EntryExitSource, string> = {
  'gate_reader': 'Gate reader',
  'manual_correction': 'Manual correction',
  'auto_sweep': 'Auto sweep',
};

export const EquipmentStatus = {
  InService: 'in_service',
  OutOfService: 'out_of_service',
  UnderMaintenance: 'under_maintenance',
  Retired: 'retired',
} as const;

export type EquipmentStatus = (typeof EquipmentStatus)[keyof typeof EquipmentStatus];

export const EquipmentStatusLabels: Record<EquipmentStatus, string> = {
  'in_service': 'In service',
  'out_of_service': 'Out of service',
  'under_maintenance': 'Under maintenance',
  'retired': 'Retired',
};

export const EvacuationStatus = {
  Open: 'open',
  Closed: 'closed',
} as const;

export type EvacuationStatus = (typeof EvacuationStatus)[keyof typeof EvacuationStatus];

export const EvacuationStatusLabels: Record<EvacuationStatus, string> = {
  'open': 'Open',
  'closed': 'Closed',
};

export const EvidenceType = {
  Snapshot: 'snapshot',
  RfidZoneSnapshot: 'rfid_zone_snapshot',
  PpeViolation: 'ppe_violation',
  Document: 'document',
  Note: 'note',
} as const;

export type EvidenceType = (typeof EvidenceType)[keyof typeof EvidenceType];

export const EvidenceTypeLabels: Record<EvidenceType, string> = {
  'snapshot': 'Snapshot',
  'rfid_zone_snapshot': 'RFID zone snapshot',
  'ppe_violation': 'PPE violation',
  'document': 'Document',
  'note': 'Note',
};

export const GasAlarmLevel = {
  Warning: 'warning',
  Alarm: 'alarm',
} as const;

export type GasAlarmLevel = (typeof GasAlarmLevel)[keyof typeof GasAlarmLevel];

export const GasAlarmLevelLabels: Record<GasAlarmLevel, string> = {
  'warning': 'Warning',
  'alarm': 'Alarm',
};

export const GasType = {
  Lel: 'lel',
  H2s: 'h2s',
  O2Low: 'o2_low',
  O2High: 'o2_high',
  Co: 'co',
  Co2: 'co2',
} as const;

export type GasType = (typeof GasType)[keyof typeof GasType];

export const GasTypeLabels: Record<GasType, string> = {
  'lel': 'LEL',
  'h2s': 'H₂S',
  'o2_low': 'O₂ low',
  'o2_high': 'O₂ high',
  'co': 'CO',
  'co2': 'CO₂',
};

export const HardwareStatus = {
  Online: 'online',
  Offline: 'offline',
  Degraded: 'degraded',
  Fault: 'fault',
  Maintenance: 'maintenance',
  Retired: 'retired',
} as const;

export type HardwareStatus = (typeof HardwareStatus)[keyof typeof HardwareStatus];

export const HardwareStatusLabels: Record<HardwareStatus, string> = {
  'online': 'Online',
  'offline': 'Offline',
  'degraded': 'Degraded',
  'fault': 'Fault',
  'maintenance': 'Maintenance',
  'retired': 'Retired',
};

export const IncidentSeverity = {
  Low: 'low',
  Medium: 'medium',
  High: 'high',
  Critical: 'critical',
} as const;

export type IncidentSeverity = (typeof IncidentSeverity)[keyof typeof IncidentSeverity];

export const IncidentSeverityLabels: Record<IncidentSeverity, string> = {
  'low': 'Low',
  'medium': 'Medium',
  'high': 'High',
  'critical': 'Critical',
};

export const IncidentSource = {
  Manual: 'manual',
  FromAlert: 'from_alert',
} as const;

export type IncidentSource = (typeof IncidentSource)[keyof typeof IncidentSource];

export const IncidentSourceLabels: Record<IncidentSource, string> = {
  'manual': 'Manual',
  'from_alert': 'From alert',
};

export const IncidentStatus = {
  Open: 'open',
  UnderReview: 'under_review',
  Classified: 'classified',
  Closed: 'closed',
} as const;

export type IncidentStatus = (typeof IncidentStatus)[keyof typeof IncidentStatus];

export const IncidentStatusLabels: Record<IncidentStatus, string> = {
  'open': 'Open',
  'under_review': 'Under review',
  'classified': 'Classified',
  'closed': 'Closed',
};

export const IncidentType = {
  Injury: 'injury',
  NearMiss: 'near_miss',
  PropertyDamage: 'property_damage',
  Environmental: 'environmental',
  Other: 'other',
} as const;

export type IncidentType = (typeof IncidentType)[keyof typeof IncidentType];

export const IncidentTypeLabels: Record<IncidentType, string> = {
  'injury': 'Injury',
  'near_miss': 'Near miss',
  'property_damage': 'Property damage',
  'environmental': 'Environmental',
  'other': 'Other',
};

export const IngestStream = {
  TagReadings: 'tag_readings',
  PpeViolations: 'ppe_violations',
  GasReadings: 'gas_readings',
  EnvironmentalReadings: 'environmental_readings',
} as const;

export type IngestStream = (typeof IngestStream)[keyof typeof IngestStream];

export const InspectionOutcome = {
  Pass: 'pass',
  Fail: 'fail',
  PassWithNotes: 'pass_with_notes',
} as const;

export type InspectionOutcome = (typeof InspectionOutcome)[keyof typeof InspectionOutcome];

export const InspectionOutcomeLabels: Record<InspectionOutcome, string> = {
  'pass': 'Pass',
  'fail': 'Fail',
  'pass_with_notes': 'Pass with notes',
};

export const Involvement = {
  Involved: 'involved',
  Witness: 'witness',
  PresentInZone: 'present_in_zone',
} as const;

export type Involvement = (typeof Involvement)[keyof typeof Involvement];

export const InvolvementLabels: Record<Involvement, string> = {
  'involved': 'Involved',
  'witness': 'Witness',
  'present_in_zone': 'Present in zone',
};

export const LsrCategory = {
  MissingPpe: 'missing_ppe',
  RedZoneIntrusion: 'red_zone_intrusion',
  UnauthorizedZoneAccess: 'unauthorized_zone_access',
  HeightWithoutHarness: 'height_without_harness',
  WorkerDown: 'worker_down',
  ZoneOccupancyExceeded: 'zone_occupancy_exceeded',
  WorkingWithoutPermit: 'working_without_permit',
  HotWorkWithoutFireWatch: 'hot_work_without_fire_watch',
  SimopsViolation: 'simops_violation',
} as const;

export type LsrCategory = (typeof LsrCategory)[keyof typeof LsrCategory];

export const LsrCategoryLabels: Record<LsrCategory, string> = {
  'missing_ppe': 'Missing PPE',
  'red_zone_intrusion': 'Red zone intrusion',
  'unauthorized_zone_access': 'Unauthorized zone access',
  'height_without_harness': 'Height without harness',
  'worker_down': 'Worker down',
  'zone_occupancy_exceeded': 'Zone occupancy exceeded',
  'working_without_permit': 'Working without permit',
  'hot_work_without_fire_watch': 'Hot work without fire watch',
  'simops_violation': 'SIMOPS violation',
};

export const LsrStatus = {
  Open: 'open',
  Closed: 'closed',
} as const;

export type LsrStatus = (typeof LsrStatus)[keyof typeof LsrStatus];

export const LsrStatusLabels: Record<LsrStatus, string> = {
  'open': 'Open',
  'closed': 'Closed',
};

export const MaintenanceType = {
  Preventive: 'preventive',
  Corrective: 'corrective',
} as const;

export type MaintenanceType = (typeof MaintenanceType)[keyof typeof MaintenanceType];

export const MaintenanceTypeLabels: Record<MaintenanceType, string> = {
  'preventive': 'Preventive',
  'corrective': 'Corrective',
};

export const MusterStatus = {
  Unaccounted: 'unaccounted',
  Accounted: 'accounted',
} as const;

export type MusterStatus = (typeof MusterStatus)[keyof typeof MusterStatus];

export const MusterStatusLabels: Record<MusterStatus, string> = {
  'unaccounted': 'Unaccounted',
  'accounted': 'Accounted',
};

export const PortableDeviceStatus = {
  Approved: 'approved',
  Revoked: 'revoked',
} as const;

export type PortableDeviceStatus = (typeof PortableDeviceStatus)[keyof typeof PortableDeviceStatus];

export const PortableDeviceStatusLabels: Record<PortableDeviceStatus, string> = {
  'approved': 'Approved',
  'revoked': 'Revoked',
};

export const ReportStatus = {
  Draft: 'draft',
  Generated: 'generated',
  Published: 'published',
} as const;

export type ReportStatus = (typeof ReportStatus)[keyof typeof ReportStatus];

export const ReportStatusLabels: Record<ReportStatus, string> = {
  'draft': 'Draft',
  'generated': 'Generated',
  'published': 'Published',
};

export const ReturnStatus = {
  Ok: 'ok',
  Damaged: 'damaged',
  NeedsService: 'needs_service',
} as const;

export type ReturnStatus = (typeof ReturnStatus)[keyof typeof ReturnStatus];

export const ReturnStatusLabels: Record<ReturnStatus, string> = {
  'ok': 'OK',
  'damaged': 'Damaged',
  'needs_service': 'Needs service',
};

export const ReviewStatus = {
  Unreviewed: 'unreviewed',
  Confirmed: 'confirmed',
  FalsePositive: 'false_positive',
} as const;

export type ReviewStatus = (typeof ReviewStatus)[keyof typeof ReviewStatus];

export const ReviewStatusLabels: Record<ReviewStatus, string> = {
  'unreviewed': 'Unreviewed',
  'confirmed': 'Confirmed',
  'false_positive': 'False positive',
};

export const ScheduleType = {
  Inspection: 'inspection',
  Service: 'service',
} as const;

export type ScheduleType = (typeof ScheduleType)[keyof typeof ScheduleType];

export const ScheduleTypeLabels: Record<ScheduleType, string> = {
  'inspection': 'Inspection',
  'service': 'Service',
};

export const TagStatus = {
  InStock: 'in_stock',
  Assigned: 'assigned',
  Lost: 'lost',
  Damaged: 'damaged',
  Retired: 'retired',
} as const;

export type TagStatus = (typeof TagStatus)[keyof typeof TagStatus];

export const TagStatusLabels: Record<TagStatus, string> = {
  'in_stock': 'In stock',
  'assigned': 'Assigned',
  'lost': 'Lost',
  'damaged': 'Damaged',
  'retired': 'Retired',
};

export const ThresholdDirection = {
  Above: 'above',
  Below: 'below',
} as const;

export type ThresholdDirection = (typeof ThresholdDirection)[keyof typeof ThresholdDirection];

export const ThresholdDirectionLabels: Record<ThresholdDirection, string> = {
  'above': 'Above',
  'below': 'Below',
};

export const ViolationType = {
  MissingHelmet: 'missing_helmet',
  MissingVest: 'missing_vest',
  MissingHarness: 'missing_harness',
  MissingMask: 'missing_mask',
} as const;

export type ViolationType = (typeof ViolationType)[keyof typeof ViolationType];

export const ViolationTypeLabels: Record<ViolationType, string> = {
  'missing_helmet': 'Missing helmet',
  'missing_vest': 'Missing vest',
  'missing_harness': 'Missing harness',
  'missing_mask': 'Missing mask',
};

export const WorkerType = {
  Employee: 'employee',
  Contractor: 'contractor',
  Visitor: 'visitor',
} as const;

export type WorkerType = (typeof WorkerType)[keyof typeof WorkerType];

export const WorkerTypeLabels: Record<WorkerType, string> = {
  'employee': 'Employee',
  'contractor': 'Contractor',
  'visitor': 'Visitor',
};

export const ZoneType = {
  Work: 'work',
  Gate: 'gate',
  RestrictedRed: 'restricted_red',
  HeightWork: 'height_work',
  MusterPoint: 'muster_point',
  Laydown: 'laydown',
  Other: 'other',
} as const;

export type ZoneType = (typeof ZoneType)[keyof typeof ZoneType];

export const ZoneTypeLabels: Record<ZoneType, string> = {
  'work': 'Work',
  'gate': 'Gate',
  'restricted_red': 'Restricted (red)',
  'height_work': 'Height work',
  'muster_point': 'Muster point',
  'laydown': 'Laydown',
  'other': 'Other',
};

// --- Permission catalogue (DOC-03) ---
// Updated by `php artisan ir4:export-permissions`.
export const Permission = {
  ViewLiveCameras: 'view-live-cameras',
  ViewPpe: 'view-ppe',
  ReviewPpe: 'review-ppe',
  ExportPpeReports: 'export-ppe-reports',
  ViewTracking: 'view-tracking',
  ViewWorkerIdentity: 'view-worker-identity',
  ManageWorkers: 'manage-workers',
  ManageTags: 'manage-tags',
  ManageZones: 'manage-zones',
  ViewEntryExit: 'view-entry-exit',
  ManagePortableDevices: 'manage-portable-devices',
  TriggerEvacuation: 'trigger-evacuation',
  ManageEvacuation: 'manage-evacuation',
  ViewGas: 'view-gas',
  ManageGasThresholds: 'manage-gas-thresholds',
  AcknowledgeAlerts: 'acknowledge-alerts',
  ConfigureAlerts: 'configure-alerts',
  ViewEquipment: 'view-equipment',
  ManageEquipment: 'manage-equipment',
  ViewIncidents: 'view-incidents',
  LogIncidents: 'log-incidents',
  ClassifyIncidents: 'classify-incidents',
  ViewLsr: 'view-lsr',
  LogLsr: 'log-lsr',
  CloseLsr: 'close-lsr',
  ViewReports: 'view-reports',
  GenerateReports: 'generate-reports',
  PublishReports: 'publish-reports',
  LogVehicleViolations: 'log-vehicle-violations',
  ViewDashboard: 'view-dashboard',
  ViewAuditLog: 'view-audit-log',
  ManageUsers: 'manage-users',
  ManageRoles: 'manage-roles',
  ManageDevices: 'manage-devices',
  ManageSettings: 'manage-settings',
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
