<?php

it('writes and checks the TypeScript enum mirror', function (): void {
    $path = resource_path('js/types/enums.ts');

    $this->artisan('ir4:export-enums')->assertSuccessful();

    $synced = file_get_contents($path);
    expect($synced)->toBeString()
        ->and($synced)->toContain('export const PermitStatus')
        ->and($synced)->toContain('AUTO-GENERATED by `php artisan ir4:export-enums`');

    $this->artisan('ir4:export-enums', ['--check' => true])->assertSuccessful();

    file_put_contents($path, $synced."\n");
    $this->artisan('ir4:export-enums', ['--check' => true])->assertFailed();

    file_put_contents($path, $synced);
    $this->artisan('ir4:export-enums', ['--check' => true])->assertSuccessful();
});
