#!/usr/bin/env bash
# Interactive edge config — writes configs/secrets.local.env + updates YAML refs.
# Usage (from EdgeCompute/):  ./scripts/configure.sh
set -euo pipefail

EDGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="${EDGE_ROOT}/configs"
SECRETS_LOCAL="${CONFIG_DIR}/secrets.local.env"
GAS_YAML="${CONFIG_DIR}/gas.yaml"
RFID_YAML="${CONFIG_DIR}/rfid.yaml"

# shellcheck source=/dev/null
if [[ -f "${CONFIG_DIR}/secrets.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${CONFIG_DIR}/secrets.env"
  set +a
fi
if [[ -f "${SECRETS_LOCAL}" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${SECRETS_LOCAL}"
  set +a
fi

prompt() {
  local label="$1"
  local current="${2:-}"
  local value
  if [[ -n "${current}" ]]; then
    read -r -p "${label} [${current}]: " value
    echo "${value:-$current}"
  else
    read -r -p "${label}: " value
    echo "${value}"
  fi
}

prompt_secret() {
  local label="$1"
  local current="${2:-}"
  local value
  if [[ -n "${current}" ]]; then
    read -r -s -p "${label} [set — Enter to keep]: " value
    echo >&2
    echo "${value:-$current}"
  else
    read -r -s -p "${label}: " value
    echo >&2
    echo "${value}"
  fi
}

echo "==> IR4 Edge configure"
echo "    Config dir: ${CONFIG_DIR}"
echo "    Writes:     ${SECRETS_LOCAL} (+ updates device_ref / reader_ref in YAML)"
echo

BASE_URL="$(prompt "IR4_BASE_URL" "${IR4_BASE_URL:-http://192.168.3.149:9100}")"
GAS_REF="$(prompt "Gas device_ref" "$(grep -E '^\s*device_ref:' "${GAS_YAML}" | head -1 | awk '{print $2}' | tr -d '"')")"
RFID_REF="$(prompt "RFID reader_ref" "$(grep -E '^\s*reader_ref:' "${RFID_YAML}" | head -1 | awk '{print $2}' | tr -d '"')")"
MQTT_TOPIC="$(prompt "MQTT topic" "$(grep -E '^\s*topic:' "${RFID_YAML}" | head -1 | awk '{print $2}' | tr -d '"')")"

GAS_UUID="$(prompt "IR4_GAS_DEVICE_UUID" "${IR4_GAS_DEVICE_UUID:-}")"
GAS_TOKEN="$(prompt_secret "IR4_GAS_DEVICE_TOKEN" "${IR4_GAS_DEVICE_TOKEN:-}")"
RFID_UUID="$(prompt "IR4_RFID_DEVICE_UUID" "${IR4_RFID_DEVICE_UUID:-}")"
RFID_TOKEN="$(prompt_secret "IR4_RFID_DEVICE_TOKEN" "${IR4_RFID_DEVICE_TOKEN:-}")"
MQTT_USER="$(prompt "IR4_MQTT_USERNAME" "${IR4_MQTT_USERNAME:-ir4-rfid}")"
MQTT_PASS="$(prompt_secret "IR4_MQTT_PASSWORD" "${IR4_MQTT_PASSWORD:-}")"

umask 077
cat > "${SECRETS_LOCAL}" <<EOF
# Generated by scripts/configure.sh — gitignored machine overrides
IR4_BASE_URL=${BASE_URL}
IR4_GAS_DEVICE_TOKEN=${GAS_TOKEN}
IR4_GAS_DEVICE_UUID=${GAS_UUID}
IR4_RFID_DEVICE_TOKEN=${RFID_TOKEN}
IR4_RFID_DEVICE_UUID=${RFID_UUID}
IR4_MQTT_USERNAME=${MQTT_USER}
IR4_MQTT_PASSWORD=${MQTT_PASS}
EOF
chmod 600 "${SECRETS_LOCAL}"

# Update YAML refs in-place (portable sed).
python3 - <<PY
from pathlib import Path
import re

def set_key(path: Path, key: str, value: str) -> None:
    text = path.read_text(encoding="utf-8")
    pattern = rf"(^\\s*{re.escape(key)}:\\s*).*$"
    repl = rf'\\1"{value}"'
    new, n = re.subn(pattern, repl, text, count=1, flags=re.M)
    if n == 0:
        raise SystemExit(f"key {key} not found in {path}")
    path.write_text(new, encoding="utf-8")

set_key(Path("${GAS_YAML}"), "device_ref", "${GAS_REF}")
set_key(Path("${RFID_YAML}"), "reader_ref", "${RFID_REF}")
set_key(Path("${RFID_YAML}"), "topic", "${MQTT_TOPIC}")
print("Updated", "${GAS_YAML}", "and", "${RFID_YAML}")
PY

echo
echo "==> Done."
echo "    Secrets: ${SECRETS_LOCAL}"
echo "    Dry-run: ir4-gas-agent --dry-run"
echo "    Dry-run: ir4-rfid-agent --dry-run"
echo "    Enable:  sudo systemctl enable --now ir4-gas-agent ir4-rfid-agent"
