#!/usr/bin/env bash
# Interactive setup — only prompts for services enabled in edge.yaml.
# Prefer: ir4-edge setup
set -euo pipefail

EDGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="${EDGE_ROOT}/configs"
SECRETS="${CONFIG_DIR}/secrets.env"
EXAMPLE="${CONFIG_DIR}/secrets.example.env"
GAS_YAML="${CONFIG_DIR}/gas.yaml"
RFID_YAML="${CONFIG_DIR}/rfid.yaml"
ENABLE_AFTER=0

for arg in "$@"; do
  case "${arg}" in
    --enable|--up) ENABLE_AFTER=1 ;;
    -h|--help) echo "Usage: $0 [--up]"; exit 0 ;;
  esac
done

# shellcheck source=/dev/null
source "${EDGE_ROOT}/deploy/host_lib.sh"
load_edge_yaml
[[ -f "${SECRETS}" ]] || cp "${EXAMPLE}" "${SECRETS}"
load_secret_env

prompt() {
  local label="$1" current="${2:-}" value
  if [[ -n "${current}" ]]; then
    read -r -p "${label} [${current}]: " value
    echo "${value:-$current}"
  else
    read -r -p "${label}: " value
    echo "${value}"
  fi
}

prompt_secret() {
  local label="$1" current="${2:-}" value
  if [[ -n "${current}" ]]; then
    read -r -s -p "${label} [set — Enter to keep]: " value; echo >&2
    echo "${value:-$current}"
  else
    read -r -s -p "${label}: " value; echo >&2
    echo "${value}"
  fi
}

yaml_val() { grep -E "^[[:space:]]*$2:" "$1" | head -1 | awk '{print $2}' | tr -d '"'; }

echo "==> ir4-edge setup (gas=${EDGE_ENABLE_GAS} rfid=${EDGE_ENABLE_RFID})"
BASE_URL="$(prompt "IR4_BASE_URL" "${IR4_BASE_URL:-http://192.168.8.40:9100}")"
[[ "${BASE_URL}" == http* && "${BASE_URL}" != *" "* ]] || {
  echo "ERROR: bad IR4_BASE_URL" >&2; exit 1
}

export IR4_SETUP_BASE_URL="${BASE_URL}"
export IR4_SETUP_ENABLE_GAS="${EDGE_ENABLE_GAS}"
export IR4_SETUP_ENABLE_RFID="${EDGE_ENABLE_RFID}"

if [[ "${EDGE_ENABLE_GAS}" == "true" ]]; then
  GAS_REF="$(prompt "IR4_GAS_DEVICE_REF" "${IR4_GAS_DEVICE_REF:-$(yaml_val "${GAS_YAML}" device_ref)}")"
  export IR4_SETUP_GAS_REF="${GAS_REF}"
  export IR4_SETUP_GAS_UUID="$(prompt "IR4_GAS_DEVICE_UUID" "${IR4_GAS_DEVICE_UUID:-}")"
  export IR4_SETUP_GAS_TOKEN="$(prompt_secret "IR4_GAS_DEVICE_TOKEN" "${IR4_GAS_DEVICE_TOKEN:-}")"
fi

if [[ "${EDGE_ENABLE_RFID}" == "true" ]]; then
  RFID_REF="$(prompt "IR4_RFID_READER_REF" "${IR4_RFID_READER_REF:-$(yaml_val "${RFID_YAML}" reader_ref)}")"
  MQTT_TOPIC="$(prompt "IR4_RFID_MQTT_TOPIC" "${IR4_RFID_MQTT_TOPIC:-$(yaml_val "${RFID_YAML}" topic)}")"
  export IR4_SETUP_RFID_REF="${RFID_REF}"
  export IR4_SETUP_MQTT_TOPIC="${MQTT_TOPIC}"
  export IR4_SETUP_RFID_UUID="$(prompt "IR4_RFID_DEVICE_UUID" "${IR4_RFID_DEVICE_UUID:-}")"
  export IR4_SETUP_RFID_TOKEN="$(prompt_secret "IR4_RFID_DEVICE_TOKEN" "${IR4_RFID_DEVICE_TOKEN:-}")"
  export IR4_SETUP_MQTT_USER="$(prompt "IR4_MQTT_USERNAME" "${IR4_MQTT_USERNAME:-ir4-rfid}")"
  export IR4_SETUP_MQTT_PASS="$(prompt_secret "IR4_MQTT_PASSWORD" "${IR4_MQTT_PASSWORD:-}")"
  export IR4_SETUP_MQTT_FXR90="$(prompt_secret "IR4_MQTT_FXR90_PASSWORD" "${IR4_MQTT_FXR90_PASSWORD:-${IR4_SETUP_MQTT_PASS}}")"
  export IR4_SETUP_MQTT_AUTH="$(prompt "IR4_MQTT_USE_AUTH (0=anonymous)" "${IR4_MQTT_USE_AUTH:-0}")"
fi

umask 077
python3 - "${SECRETS}" <<'PY'
import os
import sys
from pathlib import Path

secrets_path = Path(sys.argv[1])

existing = {}
if secrets_path.is_file():
    for raw in secrets_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        existing[key.strip()] = value.strip().strip("'").strip('"')

existing["IR4_BASE_URL"] = os.environ["IR4_SETUP_BASE_URL"]
if os.environ.get("IR4_SETUP_ENABLE_GAS") == "true":
    existing["IR4_GAS_DEVICE_REF"] = os.environ.get("IR4_SETUP_GAS_REF", "")
    existing["IR4_GAS_DEVICE_TOKEN"] = os.environ.get("IR4_SETUP_GAS_TOKEN", "")
    existing["IR4_GAS_DEVICE_UUID"] = os.environ.get("IR4_SETUP_GAS_UUID", "")
if os.environ.get("IR4_SETUP_ENABLE_RFID") == "true":
    existing["IR4_RFID_READER_REF"] = os.environ.get("IR4_SETUP_RFID_REF", "")
    existing["IR4_RFID_MQTT_TOPIC"] = os.environ.get("IR4_SETUP_MQTT_TOPIC", "")
    existing["IR4_RFID_DEVICE_TOKEN"] = os.environ.get("IR4_SETUP_RFID_TOKEN", "")
    existing["IR4_RFID_DEVICE_UUID"] = os.environ.get("IR4_SETUP_RFID_UUID", "")
    existing["IR4_MQTT_USE_AUTH"] = os.environ.get("IR4_SETUP_MQTT_AUTH", "0")
    existing["IR4_MQTT_USERNAME"] = os.environ.get("IR4_SETUP_MQTT_USER", "ir4-rfid")
    existing["IR4_MQTT_PASSWORD"] = os.environ.get("IR4_SETUP_MQTT_PASS", "")
    existing["IR4_MQTT_FXR90_PASSWORD"] = os.environ.get("IR4_SETUP_MQTT_FXR90", "")

order = [
    "IR4_BASE_URL",
    "IR4_GAS_DEVICE_REF",
    "IR4_GAS_DEVICE_TOKEN",
    "IR4_GAS_DEVICE_UUID",
    "IR4_RFID_READER_REF",
    "IR4_RFID_MQTT_TOPIC",
    "IR4_RFID_DEVICE_TOKEN",
    "IR4_RFID_DEVICE_UUID",
    "IR4_MQTT_USE_AUTH",
    "IR4_MQTT_USERNAME",
    "IR4_MQTT_PASSWORD",
    "IR4_MQTT_FXR90_PASSWORD",
    "IR4_DRY_RUN",
]
lines = ["# Generated by ir4-edge setup"]
seen = set()
for key in order:
    if key not in existing:
        continue
    value = existing[key].replace("\\", "\\\\").replace('"', '\\"')
    lines.append('{}="{}"'.format(key, value))
    seen.add(key)
for key, value in sorted(existing.items()):
    if key in seen:
        continue
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    lines.append('{}="{}"'.format(key, escaped))
secrets_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("Wrote", secrets_path)
print("Per-pole refs live in secrets.env (IR4_GAS_DEVICE_REF / IR4_RFID_READER_REF / IR4_RFID_MQTT_TOPIC).")
PY
chmod 640 "${SECRETS}"

echo "==> Done → ${SECRETS}"
[[ "${ENABLE_AFTER}" -eq 1 ]] && sudo "${EDGE_ROOT}/scripts/enable_services.sh"
echo "Next: ir4-edge doctor && ir4-edge status"
